-- LAYER: synthetic. Simulated business data that Olist does not provide, generated by
-- generator/synthesize.py (fixed seed, documented formulas in docs/SYNTHETIC_DATA.md).
--   syn_*  read-only plans / history (targets, SLA rules, forecasts, inventory snapshots)
--   ops_*  operational records the application (and the agent, after confirmation) can change
-- Nothing here is an Olist fact. Every table carries a COMMENT starting with its layer; the API's
-- data dictionary and catalogue read those comments.
DROP TABLE IF EXISTS syn_monthly_sales_targets, syn_delivery_sla_rules, syn_monthly_sales_forecasts,
  syn_inventory_snapshots, ops_product_listings, ops_restock_orders, ops_support_tickets,
  ops_review_replies, ops_promotions, ops_price_changes, ops_seller_flags, ops_action_log CASCADE;

-- grain: one row per target month x customer state x scenario
CREATE TABLE syn_monthly_sales_targets (
  target_id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  target_month    date NOT NULL CHECK (target_month = date_trunc('month', target_month)),
  customer_state  text NOT NULL,
  revenue_target  numeric(14,2) NOT NULL CHECK (revenue_target > 0),
  order_target    integer NOT NULL CHECK (order_target > 0),
  scenario_name   text NOT NULL DEFAULT 'baseline',
  method          text NOT NULL,
  UNIQUE (target_month, customer_state, scenario_name));

-- grain: one row per destination state x rule version (effective-dated)
CREATE TABLE syn_delivery_sla_rules (
  sla_rule_id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  destination_state      text NOT NULL,
  destination_region     text NOT NULL,
  effective_from         date NOT NULL,
  effective_to           date,               -- NULL = still in force
  expected_delivery_days integer NOT NULL CHECK (expected_delivery_days > 0),
  sla_threshold_days     integer NOT NULL,   -- breach when delivery_days > threshold
  scenario_name          text NOT NULL DEFAULT 'baseline',
  CHECK (sla_threshold_days >= expected_delivery_days),
  CHECK (effective_to IS NULL OR effective_to >= effective_from),
  UNIQUE (destination_state, effective_from, scenario_name));

-- grain: one row per forecast month x customer state x scenario
CREATE TABLE syn_monthly_sales_forecasts (
  forecast_id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  forecast_month    date NOT NULL CHECK (forecast_month = date_trunc('month', forecast_month)),
  customer_state    text NOT NULL,
  predicted_revenue numeric(14,2) NOT NULL CHECK (predicted_revenue >= 0),
  scenario_name     text NOT NULL,           -- baseline | optimistic | conservative
  forecast_method   text NOT NULL,
  model_version     text NOT NULL,
  data_cutoff       date NOT NULL,           -- last month of actuals the model saw
  horizon_months    integer NOT NULL CHECK (horizon_months >= 1),
  generated_at      date NOT NULL,
  UNIQUE (forecast_month, customer_state, scenario_name, model_version));

-- grain: one row per month-end snapshot date x product
CREATE TABLE syn_inventory_snapshots (
  snapshot_date   date NOT NULL,
  product_id      text NOT NULL REFERENCES raw_products(product_id),
  stock_quantity  integer NOT NULL CHECK (stock_quantity >= 0),
  reorder_point   integer NOT NULL CHECK (reorder_point >= 0),
  unit_cost       numeric(12,2) NOT NULL CHECK (unit_cost > 0),
  scenario_name   text NOT NULL DEFAULT 'baseline',
  PRIMARY KEY (snapshot_date, product_id, scenario_name));

-- grain: one row per listed product (products sold in the 6 months before as_of_date). Current state.
CREATE TABLE ops_product_listings (
  product_id      text PRIMARY KEY REFERENCES raw_products(product_id),
  list_price      numeric(12,2) NOT NULL CHECK (list_price > 0),
  unit_cost       numeric(12,2) NOT NULL CHECK (unit_cost > 0),
  stock_quantity  integer NOT NULL CHECK (stock_quantity >= 0),
  reorder_point   integer NOT NULL CHECK (reorder_point >= 0),
  order_up_to     integer NOT NULL CHECK (order_up_to >= reorder_point),
  lead_time_days  integer NOT NULL CHECK (lead_time_days > 0),
  status          text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
  updated_at      timestamp NOT NULL);

CREATE TABLE ops_restock_orders (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code            text GENERATED ALWAYS AS ('RST-' || lpad(id::text, 6, '0')) STORED UNIQUE,
  product_id      text NOT NULL REFERENCES ops_product_listings(product_id),
  quantity        integer NOT NULL CHECK (quantity > 0),
  status          text NOT NULL CHECK (status IN ('placed', 'in_transit', 'received', 'canceled')),
  created_at      timestamp NOT NULL,
  expected_arrival date NOT NULL,
  received_at     timestamp,
  created_by      text NOT NULL,
  note            text);

CREATE TABLE ops_support_tickets (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code            text GENERATED ALWAYS AS ('TCK-' || lpad(id::text, 6, '0')) STORED UNIQUE,
  order_id        text NOT NULL REFERENCES raw_orders(order_id),
  customer_unique_id text,
  seller_id       text REFERENCES raw_sellers(seller_id),
  category        text NOT NULL CHECK (category IN ('late_delivery', 'not_received', 'damaged_item',
                    'wrong_item', 'product_quality', 'refund_request', 'other')),
  priority        text NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  status          text NOT NULL CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  subject         text NOT NULL,
  assignee        text,
  created_at      timestamp NOT NULL,
  resolved_at     timestamp,
  created_by      text NOT NULL,
  notes           text,
  CHECK (resolved_at IS NULL OR resolved_at >= created_at));

CREATE TABLE ops_review_replies (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code            text GENERATED ALWAYS AS ('RPL-' || lpad(id::text, 6, '0')) STORED UNIQUE,
  review_id       text NOT NULL,
  order_id        text NOT NULL REFERENCES raw_orders(order_id),
  reply_text      text NOT NULL CHECK (length(reply_text) BETWEEN 2 AND 2000),
  created_at      timestamp NOT NULL,
  created_by      text NOT NULL);

CREATE TABLE ops_promotions (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code            text GENERATED ALWAYS AS ('PRM-' || lpad(id::text, 4, '0')) STORED UNIQUE,
  name            text NOT NULL,
  product_category text,                     -- NULL = all categories
  customer_state  text,                      -- NULL = all states
  discount_pct    numeric(5,2) NOT NULL CHECK (discount_pct > 0 AND discount_pct <= 70),
  start_date      date NOT NULL,
  end_date        date NOT NULL,
  canceled        boolean NOT NULL DEFAULT false,
  created_at      timestamp NOT NULL,
  created_by      text NOT NULL,
  CHECK (end_date >= start_date));

CREATE TABLE ops_price_changes (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code            text GENERATED ALWAYS AS ('PRC-' || lpad(id::text, 6, '0')) STORED UNIQUE,
  product_id      text NOT NULL REFERENCES ops_product_listings(product_id),
  old_price       numeric(12,2) NOT NULL,
  new_price       numeric(12,2) NOT NULL CHECK (new_price > 0),
  reason          text,
  created_at      timestamp NOT NULL,
  created_by      text NOT NULL);

CREATE TABLE ops_seller_flags (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code            text GENERATED ALWAYS AS ('FLG-' || lpad(id::text, 5, '0')) STORED UNIQUE,
  seller_id       text NOT NULL REFERENCES raw_sellers(seller_id),
  reason          text NOT NULL CHECK (reason IN ('high_late_rate', 'low_review_score',
                    'high_cancellation', 'policy_violation', 'other')),
  severity        text NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
  status          text NOT NULL CHECK (status IN ('open', 'resolved', 'dismissed')),
  note            text,
  created_at      timestamp NOT NULL,
  created_by      text NOT NULL);

-- every write made through the API: who, what, before/after images (used for undo and verification)
CREATE TABLE ops_action_log (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code            text GENERATED ALWAYS AS ('ACT-' || lpad(id::text, 6, '0')) STORED UNIQUE,
  api_id          text NOT NULL,
  actor           text NOT NULL,             -- user | agent
  params          jsonb NOT NULL,
  changes         jsonb NOT NULL,            -- [{table, pk_col, pk, op, before, after}]
  result          jsonb,
  sim_time        timestamp NOT NULL,        -- simulated business time (as_of_date)
  created_at      timestamptz NOT NULL DEFAULT now(),
  undone_at       timestamptz,
  undone_by       text);

CREATE INDEX ON syn_inventory_snapshots (product_id);
CREATE INDEX ON ops_support_tickets (order_id);
CREATE INDEX ON ops_support_tickets (status, created_at);
CREATE INDEX ON ops_review_replies (review_id, order_id);
CREATE INDEX ON ops_restock_orders (product_id, status);
CREATE INDEX ON ops_seller_flags (seller_id);
CREATE INDEX ON ops_price_changes (product_id);
-- (review_id, order_id) identifies a review; fact tables are rebuilt so index the raw table here
CREATE INDEX IF NOT EXISTS raw_reviews_review_order ON raw_reviews (review_id, order_id);
CREATE INDEX IF NOT EXISTS raw_reviews_order ON raw_reviews (order_id);
CREATE INDEX IF NOT EXISTS raw_order_items_order ON raw_order_items (order_id);
CREATE INDEX IF NOT EXISTS raw_order_items_seller ON raw_order_items (seller_id);
CREATE INDEX IF NOT EXISTS raw_order_items_product ON raw_order_items (product_id);
CREATE INDEX IF NOT EXISTS raw_payments_order ON raw_payments (order_id);
CREATE INDEX IF NOT EXISTS raw_orders_customer ON raw_orders (customer_id);

-- ---------------------------------------------------------------- data dictionary (read by the API)
-- (comments for raw_*, core_* and fact_* tables are at the end of 10_facts.sql)
COMMENT ON TABLE syn_monthly_sales_targets IS 'synthetic: simulated monthly revenue/order targets per customer state (not real Olist targets)';
COMMENT ON TABLE syn_delivery_sla_rules IS 'synthetic: simulated delivery SLA per destination state, effective-dated (not Olist estimated dates)';
COMMENT ON TABLE syn_monthly_sales_forecasts IS 'synthetic: model-generated revenue forecasts per state and scenario (estimates, not sales)';
COMMENT ON TABLE syn_inventory_snapshots IS 'synthetic: simulated month-end stock per product, driven by real Olist unit sales';
COMMENT ON TABLE ops_product_listings IS 'synthetic: current list price, unit cost, stock and reorder settings per listed product (writable)';
COMMENT ON TABLE ops_restock_orders IS 'synthetic: purchase orders to replenish stock (writable)';
COMMENT ON TABLE ops_support_tickets IS 'synthetic: customer support tickets linked to real Olist orders (writable)';
COMMENT ON TABLE ops_review_replies IS 'synthetic: seller replies to real Olist reviews (writable)';
COMMENT ON TABLE ops_promotions IS 'synthetic: discount campaigns by category/state (writable); they did not cause observed Olist sales';
COMMENT ON TABLE ops_price_changes IS 'synthetic: history of list price changes (writable)';
COMMENT ON TABLE ops_seller_flags IS 'synthetic: seller performance flags raised by operations (writable)';
COMMENT ON TABLE ops_action_log IS 'system: audit log of every API write with before/after images, used for undo';
